### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by maximakhmatovich** [karasevIA/finik_eth#3]
When I trying to create .fap it gives a lot of errors, check screenshot

![errors](https://github.com/karasevIA/finik_eth/assets/121092282/d5749a4f-5aff-4289-a5ec-268c59cdef81)

**Comment by karasevIA** [comment]
Смотрю

**Comment by karasevIA** [comment]
Исправил

**Comment by karasevIA** [comment]
Исправил в коммите c7b67bdbbed9fc056225fb024e5c83c111ebfbfd

**Comment by maximtsepaev** [comment]
Спасибо, завтра попробую
